DIL_FINAL_FACTOR_NAME = 'final dilution factor'
DIL_SAMPLE_DESCRIPTION_NAME = 'Sample name'
DIL_TYPE_NAME = 'type'
CONC_NAME = 'Conc(copies/µL)'
FDL_NAME = "final dilution factor"
SAMPLE_NAME = "Sample"
SAMPLE_TYPE_NAME = "sample type"
SAMPLE_NUM_NAME = "Sample description 1"
WELL_RESULT_NAME = 'vg/ml'
TARGET_ID_NAME = 'target_id'
SAMPLE_ID_NAME = 'sample_id'
CV_COLNAME = 'CV [%]'
VALUE_CHECK_NAME = 'method_check'
DROPLET_THRESHOLD = int(10000)
DROPLET_CHECK_COLNAME = 'Accepted Droplets'
DROPLET_CHECK_NAME = 'droplet_check'
CONTROL_CHECK_COLNAME_ORIG = 'mean [vg/ml]'
CONTROL_CHECK_NAME = 'control_check'
WARNING_CHECK_NAME = 'warning_check'
CV_CHECK_NAME = 'cv_check'
