DIL_FINAL_FACTOR_NAME: str = 'final dilution factor'
DIL_SAMPLE_DESCRIPTION_NAME: str = 'Sample name'
DIL_TYPE_NAME: str = 'type'
CONC_NAME: str = 'Conc(copies/µL)'
FDL_NAME: str = "final dilution factor"
SAMPLE_NAME: str = "Sample"
SAMPLE_TYPE_NAME: str = "sample type"
SAMPLE_NUM_NAME: str = "Sample description 1"
WELL_RESULT_NAME: str = 'vg/ml'
TARGET_ID_NAME: str = 'target_id'
SAMPLE_ID_NAME: str = 'sample_id'
CV_COLNAME: str = 'CV [%]'
VALUE_CHECK_NAME: str = 'method_check'
DROPLET_THRESHOLD: int = int(10000)
DROPLET_CHECK_COLNAME: str = 'Accepted Droplets'
DROPLET_CHECK_NAME: str = 'droplet_check'
MEAN_NAME: str = 'mean [vg/ml]'
CONTROL_CHECK_NAME: str = 'control_check'
WARNING_CHECK_NAME: str = 'warning_check'
CV_CHECK_NAME: str = 'cv_check'
STDE_NAME = 'STDE'
